### ISSUE TITLE
Crash game/world generation

### ISSUE THREAD

**Issue by Dseelis** [Dseelis/Steamcreate-CSD-#3]
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: Caused by: net.minecraft.class_148: Feature placement
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2794.method_12102(class_2794.java:486)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2806.method_20613(class_2806.java:145)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2806.md8ed26b$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2101)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	... 6 more
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: No chunk exists at [10, 8]
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_3233.method_8320(class_3233.java:3582)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at com.ordana.spelunkery.features.SculkGrowthFeature.isBlockExposedToAir(SculkGrowthFeature.java:82)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at com.ordana.spelunkery.features.SculkGrowthFeature.method_13151(SculkGrowthFeature.java:68)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2975.method_12862(class_2975.java:537)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39646(class_6796.java:56)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39648(class_6796.java:55)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39650(class_6796.java:44)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2794.method_12102(class_2794.java:466)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	... 9 more
[15:53:30] [minecraft_overworld - Light/ERROR]: Failed to light chunk [10, 12]
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: net.minecraft.class_148: Feature placement
	at net.minecraft.class_2794.method_12102(class_2794.java:486) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.md8ed26b$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2101) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
Caused by: java.lang.NullPointerException: No chunk exists at [10, 8]
	at net.minecraft.class_3233.method_8320(class_3233.java:3582) ~[client-intermediary.jar:?]
	at com.ordana.spelunkery.features.SculkGrowthFeature.isBlockExposedToAir(SculkGrowthFeature.java:82) ~[spelunkery-1.19.2-0.2.6-fabric.jar:?]
	at com.ordana.spelunkery.features.SculkGrowthFeature.method_13151(SculkGrowthFeature.java:68) ~[spelunkery-1.19.2-0.2.6-fabric.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:537) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39646(class_6796.java:56) ~[client-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_6796.method_39648(class_6796.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39650(class_6796.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:466) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.md8ed26b$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2101) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: Caused by: net.minecraft.class_148: Feature placement
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2794.method_12102(class_2794.java:486)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2806.method_20613(class_2806.java:145)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2806.md8ed26b$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2101)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	... 6 more
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: No chunk exists at [10, 8]
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_3233.method_8320(class_3233.java:3582)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at com.ordana.spelunkery.features.SculkGrowthFeature.isBlockExposedToAir(SculkGrowthFeature.java:82)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at com.ordana.spelunkery.features.SculkGrowthFeature.method_13151(SculkGrowthFeature.java:68)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2975.method_12862(class_2975.java:537)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39646(class_6796.java:56)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39648(class_6796.java:55)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_6796.method_39650(class_6796.java:44)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	at net.minecraft.class_2794.method_12102(class_2794.java:466)
[15:53:30] [C2ME worker #1/INFO]: [STDERR]: 	... 9 more
[15:53:30] [Render thread/INFO]: ?????????? ??????? ???????????: 95%
[15:53:30] [Server thread/ERROR]: Encountered an unexpected exception
java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: net.minecraft.class_148: Feature placement
	at net.minecraft.class_2794.method_12102(class_2794.java:486) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.md8ed26b$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2101) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
Caused by: java.lang.NullPointerException: No chunk exists at [10, 8]
	at net.minecraft.class_3233.method_8320(class_3233.java:3582) ~[client-intermediary.jar:?]
	at com.ordana.spelunkery.features.SculkGrowthFeature.isBlockExposedToAir(SculkGrowthFeature.java:82) ~[spelunkery-1.19.2-0.2.6-fabric.jar:?]
	at com.ordana.spelunkery.features.SculkGrowthFeature.method_13151(SculkGrowthFeature.java:68) ~[spelunkery-1.19.2-0.2.6-fabric.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:537) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39646(class_6796.java:56) ~[client-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_6796.method_39648(class_6796.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39650(class_6796.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:466) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.md8ed26b$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2101) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more

**Comment by Dseelis** [comment]
The problem was solved by rolling back the mods, the exact cause is not clear yet
