### ISSUE TITLE
Game crash/creating world

### ISSUE THREAD

**Issue by Dseelis** [Dseelis/Steamcreate-CSD-#5]
[17:09:35] [Render thread/ERROR]:
 ########## GL ERROR ##########
[17:09:35] [Render thread/ERROR]:
 @ Render
[17:09:35] [Render thread/ERROR]:
 65539: Invalid key 0
[17:09:38] [C2ME worker #2/ERROR]:
 Detected setBlock in a far chunk [-43, 2], pos: class_2338{x=-673, y=-36, z=35}, status: minecraft:features, currently generating: ResourceKey[minecraft:worldgen/placed_feature / minecraft:sculk_patch_deep_dark]
[17:09:38] [C2ME worker #2/ERROR]:
 Detected setBlock in a far chunk [-43, 2], pos: class_2338{x=-673, y=-35, z=35}, status: minecraft:features
[17:09:38] [C2ME worker #2/ERROR]:
 Detected setBlock in a far chunk [-43, 2], pos: class_2338{x=-673, y=-34, z=35}, status: minecraft:features
[17:09:38] [C2ME worker #2/ERROR]:
 Detected setBlock in a far chunk [-43, 2], pos: class_2338{x=-673, y=-34, z=35}, status: minecraft:features
[17:09:38] [C2ME worker #2/ERROR]:
 Detected setBlock in a far chunk [-43, 2], pos: class_2338{x=-673, y=-33, z=34}, status: minecraft:features
[17:09:38] [C2ME worker #2/ERROR]:
 Detected setBlock in a far chunk [-42, 2], pos: class_2338{x=-672, y=-33, z=35}, status: minecraft:features
[17:09:38] [C2ME worker #2/ERROR]:
 Detected setBlock in a far chunk [-43, 2], pos: class_2338{x=-673, y=-32, z=34}, status: minecraft:features
[17:09:38] [C2ME worker #2/ERROR]:
 Detected setBlock in a far chunk [-42, 2], pos: class_2338{x=-672, y=-32, z=35}, status: minecraft:features
[17:09:38] [C2ME worker #2/ERROR]:
 Detected setBlock in a far chunk [-43, 2], pos: class_2338{x=-673, y=-32, z=34}, status: minecraft:features
[17:09:39] [Render thread/ERROR]:
 ########## GL ERROR ##########
[17:09:39] [Render thread/ERROR]:
 @ Render
[17:09:39] [Render thread/ERROR]:
 65539: Invalid key 0
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: java.util.concurrent.CompletionException: net.minecraft.class_148: Feature placement
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: Caused by: net.minecraft.class_148: Feature placement
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at net.minecraft.class_2794.method_12102(class_2794.java:486)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at net.minecraft.class_2806.method_20613(class_2806.java:145)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at net.minecraft.class_2806.mdcbb3f9$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2101)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	... 6 more
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: Caused by: java.lang.NullPointerException: No chunk exists at [-46, -1]
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at net.minecraft.class_3233.method_8320(class_3233.java:2582)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at com.ordana.spelunkery.features.SculkGrowthFeature.exposedToAir(SculkGrowthFeature.java:93)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at com.ordana.spelunkery.features.SculkGrowthFeature.isBlockExposedToAir(SculkGrowthFeature.java:83)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at com.ordana.spelunkery.features.SculkGrowthFeature.method_13151(SculkGrowthFeature.java:68)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at net.minecraft.class_2975.method_12862(class_2975.java:537)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at net.minecraft.class_6796.method_39646(class_6796.java:56)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[17:09:42] [C2ME worker #1/INFO]:
 [STDERR]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[17:09:42] [Server thread/ERROR]:
 Encountered an unexpected exception
net.minecraft.class_148: Feature placement
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: No chunk exists at [-46, -1]
	at net.minecraft.class_3233.method_8320(class_3233.java:2582) ~[client-intermediary.jar:?]
	at com.ordana.spelunkery.features.SculkGrowthFeature.exposedToAir(SculkGrowthFeature.java:93) ~[spelunkery-1.19.2-0.2.6-fabric.jar:?]
	at com.ordana.spelunkery.features.SculkGrowthFeature.isBlockExposedToAir(SculkGrowthFeature.java:83) ~[spelunkery-1.19.2-0.2.6-fabric.jar:?]
	at com.ordana.spelunkery.features.SculkGrowthFeature.method_13151(SculkGrowthFeature.java:68) ~[spelunkery-1.19.2-0.2.6-fabric.jar:?]
	at net.minecraft.class_2975.method_12862(class_2975.java:537) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39646(class_6796.java:56) ~[client-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_6796.method_39648(class_6796.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_6796.method_39650(class_6796.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:466) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20613(class_2806.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.mdcbb3f9$c2me-threading-worldgen$lambda$runGenerationTask$0$5(class_2806.java:2101) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

**Comment by Dseelis** [comment]
the game wants access to chunks that haven't been uploaded yet.

**Comment by Dseelis** [comment]
Upgrading to a new version fixed everything.
